services:
  db:
    #container_name: postgresnewcont
    image: postgres:13
    restart: always
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=jobquest_testuser
    #   - POSTGRES_PASSWORD=test@123
    #   - POSTGRES_DB=jobquest_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: